name: Builder

on: [push, pull_request]

jobs:
  builder:
    name: Build the site
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: site

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y npm git          
          go get github.com/googlecodelabs/tools/claat

      # Build docs
      - name: Build html from markdown
        run: |
          pushd devlabs && for f in *.md; do ~/go/bin/claat export -f html "$f" ; done && pushd

      # Build site
      - name: Build html for site
        run: |
          npm install gulp-cli
          gulp dist --codelabs-dir=./devlabs

      - name: Save package
        uses: actions/upload-artifact@v2
        with:
          name: dist ${{ matrix.node-version }}
          path: ${{ github.workspace }}/site/dist/
          if-no-files-found: error
